{{- $svc := index .Values.global "frontend" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ $svc.imagePullPolicy }}
          ports:
            - containerPort: {{ $svc.containerPort }}
          envFrom:
            - configMapRef:
                name: frontend-config
          readinessProbe:
{{- toYaml $svc.readinessProbe | nindent 12 }}
          livenessProbe:
{{- toYaml $svc.livenessProbe | nindent 12 }}
          resources:
{{- toYaml $svc.resources | nindent 12 }}
