apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
# Provisioner for nfs-subdir-external-provisioner installed via Helm
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "true"
# Retain policy to ensure we don't accidentally lose database storage
reclaimPolicy: Retain
volumeBindingMode: Immediate
