{{- $mongo := .Values.global.mongodb }}
{{- range $index, $name := $mongo.instances }}
{{- if $index }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $name }}
spec:
  clusterIP: None
  ports:
    - port: {{ $mongo.servicePort }}
      targetPort: {{ $mongo.containerPort }}
  selector:
    app: {{ $name }}
{{- end }}
