{{- $svc := index .Values.global "user-profile-service" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-profile-service-config
  namespace: {{ .Values.global.namespace }}
data:
{{- toYaml $svc.config | nindent 2 }}
