{{- $svc := index .Values.global "user-profile-service" -}}
apiVersion: v1
kind: Secret
metadata:
  name: user-profile-service-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
{{- toYaml $svc.secrets | nindent 2 }}
