{{- $svc := index .Values.global "product-service" -}}
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
{{- toYaml $svc.secrets | nindent 2 }}
